# API KEY
apiVersion: passport/v1
kind: ApiKey
metadata:
  name: clone-secret-key
spec:
  name: Secret Api Key For Sender Side
  policies:
    - BucketFullAccess
    - FunctionFullAccess
---
# FUNCTION CLONE
apiVersion: function/v1
kind: Function
metadata:
  name: clone
spec:
  title: Clone Server - Sender Side
  description: "Clone and send your buckets and functions with dependencies and environments to another server"
  timeout: 300
  code: ./function/clone.js
  runtime:
    name: Node
    language: Javascript
  environment:
    - name: API_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: clone-secret-key
    - name: _IGNORE_
      value: "Dont't remove this environment !"
  dependency:
    - name: "@spica-devkit/bucket"
      version: latest
    - name: "@spica-devkit/database"
      version: latest
    - name: "node-fetch"
      version: latest
---
# TRIGGER - Initialize
apiVersion: function/v1
kind: Trigger
metadata:
  name: sender
spec:
  name: sender
  func: clone
  type: http
  httpOptions:
    method: Get
    path: /sender
---
# TRIGGER - Initialize
apiVersion: function/v1
kind: Trigger
metadata:
  name: sender-dashboard
spec:
  name: senderDashboard
  func: clone
  type: http
  httpOptions:
    method: Get
    path: /senderDashboard
---
# SENDER DASHBOARD
apiVersion: dashboard/v1
kind: Dashboard
metadata:
  name: sender-dashboard
spec:
  name: Sender
  icon: swap_vert
  components:
    - name: Export
      url: api:/fn-execute/senderDashboard
      type: card
